version: '3.3' # specify docker-compose version

# Define the services/containers to be run
services:

  # see: https://hub.docker.com/r/payara/server-full/
  payara:
    image: payara/server-full
    container_name: payara
    ports:
      - "8080:8080"
      - "8181:8181" # HTTPS listener
      - "4848:4848" # HTTPS admin listener
      - "9009:9009" # Debug port
    #    environment:
    #    JVM_ARGS: ""
    #     - "AS_ADMIN_MASTERPASSWORD=admin" #default password is `changeit`
    volumes:
      - ./deployments:/opt/payara/deployments

  # see: https://hub.docker.com/r/jboss/wildfly/
  wildfly:
    image: jboss/wildfly
    container_name: wildfly
    ports:
      - "8080:8080"
      - "9990:9990" # admin listener
    command: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0
    #    environment:
    volumes:
      - ./deployments:/opt/jboss/wildfly/standalone/deployments/

  # see: https://hub.docker.com/_/open-liberty
  liberty:
    image: open-liberty:21.0.0.2-full-java8-openj9
    container_name: liberty
    ports:
      - "9080:9080"
      - "9443:9443" # HTTPS listener
    #    command: configure.sh # use for open-liberty:kernel image.
    #    environment:
    volumes:
      - ./deployments:/config/dropins
      - ./src/test/liberty-remote:/liberty/usr/servers/myserver